import {StyleSheet} from "react-native"

export const idStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f5f5" },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#666",
    fontWeight: "500",
  },
  errorText: { fontSize: 18, color: "#999", marginTop: 16, fontWeight: "600" },
  imageContainer: { width: "100%", height: 320, position: "relative" },
  image: { width: "100%", height: "100%", resizeMode: "cover" },
  imageGradient: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 100,
  },
  imagePlaceholder: {
    width: "100%",
    height: "100%",
    backgroundColor: "#e8e8e8",
    justifyContent: "center",
    alignItems: "center",
  },
  contentCard: {
    backgroundColor: "#fff",
    marginTop: -30,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 24,
    elevation: 5,
  },
  titleSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  title: { fontSize: 28, fontWeight: "800", color: "#1a1a1a", flex: 1 },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF8E1",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 4,
  },
  badgeText: { fontSize: 12, fontWeight: "700", color: "#F57C00" },
  deskripsi: { fontSize: 16, color: "#666", lineHeight: 24, marginBottom: 20 },
  priceContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFF3E0",
    padding: 16,
    borderRadius: 16,
    marginBottom: 20,
  },
  priceLabel: { fontSize: 13, color: "#F57C00", fontWeight: "600" },
  harga: { fontSize: 26, fontWeight: "800", color: "#FF7A00" },
  actionsContainer: { flexDirection: "row", gap: 12, marginBottom: 24 },
  cartButton: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#2C3E50",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  cartButtonText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  buyButton: {
    flex: 1.5,
    flexDirection: "row",
    backgroundColor: "#FF7A00",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  buyButtonDisabled: { opacity: 0.7 },
  buyButtonText: { color: "#fff", fontWeight: "800", fontSize: 16 },
  viewRecipeButton: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#00A86B",
    paddingVertical: 18,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  viewRecipeButtonText: { color: "#fff", fontWeight: "800", fontSize: 17 },
  divider: { height: 1, backgroundColor: "#e8e8e8", marginVertical: 24 },
  manageSection: { marginTop: 8 },
  manageSectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#888",
    marginBottom: 16,
  },
  manageButtons: { flexDirection: "row", gap: 12 },
  manageButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    borderRadius: 14,
    gap: 8,
    borderWidth: 2,
  },
  manageButtonPressed: { transform: [{ scale: 0.96 }], opacity: 0.8 },
  editButton: { backgroundColor: "#E3F2FD", borderColor: "#007AFF" },
  editButtonText: { color: "#007AFF", fontWeight: "700", fontSize: 15 },
  deleteButton: { backgroundColor: "#FFEBEE", borderColor: "#FF3B30" },
  deleteButtonText: { color: "#FF3B30", fontWeight: "700", fontSize: 15 },
});
